param(
  [Parameter(Mandatory = $true)]
  [string]$InputBinary,

  [Parameter(Mandatory = $false)]
  [string]$OutputHeader = "cpm22_system_image.h",

  [Parameter(Mandatory = $false)]
  [UInt32]$BaseAddress = 0xDC00
)

if (-not (Test-Path -LiteralPath $InputBinary)) {
  throw "Input binary not found: $InputBinary"
}

if ($BaseAddress -gt 0xFFFF) {
  throw "BaseAddress must be <= 0xFFFF"
}

[byte[]]$bytes = [System.IO.File]::ReadAllBytes((Resolve-Path -LiteralPath $InputBinary))

if ($bytes.Length -eq 0) {
  throw "Input binary is empty: $InputBinary"
}

$endAddress = [UInt32]$BaseAddress + [UInt32]$bytes.Length
if ($endAddress -gt 0x10000) {
  throw ("Image exceeds 64K address space: base=0x{0:X4} size={1} end=0x{2:X5}" -f $BaseAddress, $bytes.Length, $endAddress)
}

$nl = [Environment]::NewLine
$sb = New-Object System.Text.StringBuilder

[void]$sb.Append("#pragma once$nl$nl")
[void]$sb.Append("#include <stdint.h>$nl$nl")
[void]$sb.Append("// Auto-generated from $InputBinary$nl")
[void]$sb.Append("// Generated by build_cpm22_image_header.ps1$nl")
[void]$sb.Append(("constexpr uint16_t CPM22_SYSTEM_IMAGE_BASE = 0x{0:X4};{1}" -f $BaseAddress, $nl))
[void]$sb.Append("constexpr uint8_t CPM22_SYSTEM_IMAGE[] = {$nl")

for ($i = 0; $i -lt $bytes.Length; $i += 16) {
  $count = [Math]::Min(16, $bytes.Length - $i)
  $line = "  "
  for ($j = 0; $j -lt $count; $j++) {
    $line += ("0x{0:X2}" -f $bytes[$i + $j])
    if (($i + $j) -lt ($bytes.Length - 1)) {
      $line += ", "
    }
  }
  [void]$sb.Append($line)
  [void]$sb.Append($nl)
}

[void]$sb.Append("};$nl")
[void]$sb.Append("constexpr uint32_t CPM22_SYSTEM_IMAGE_SIZE = sizeof(CPM22_SYSTEM_IMAGE);$nl")

[System.IO.File]::WriteAllText((Join-Path (Get-Location) $OutputHeader), $sb.ToString(), [System.Text.UTF8Encoding]::new($false))

Write-Host ("Wrote {0} bytes to {1} at base 0x{2:X4}" -f $bytes.Length, $OutputHeader, $BaseAddress)
